name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild test -project AdventKit.xcodeproj -scheme AdventKit -destination 'platform=OS X,arch=x86_64'
